import { Dimensions, StyleSheet } from "react-native";
const SCREEN_WIDTH=Dimensions.get('screen').width
const styles = StyleSheet.create({
  container:{
    flex:1,

  },
  header:{
    borderBottomRightRadius:15,
    borderBottomLeftRadius:15,
    padding:20,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#8AAAE5'
  },
  headerText:{
    color:'#00246B',
    fontSize:21,
    fontWeight:'600',
  },
  body:{
    width:SCREEN_WIDTH,
    marginTop:'30%',
    alignItems:'center',
  },
  questionView:{
    padding:5,
    borderRadius:10,
    alignItems:'center',
    width:SCREEN_WIDTH*.8,
    backgroundColor:'#735DA5'
  },
  questionText:{
    fontSize:21,
    color:'white'
  },
  optionView:{
    width:SCREEN_WIDTH*.8,
    marginVertical:'10%',
  },
  touchableNext:{
    marginTop:5,
    padding:5,
    backgroundColor:'#CADCFC',
    borderRadius:10,
  },
  nextText:{
    fontSize:20,
  },
  optionTouchable:{
    alignItems:'center',
    padding:10,
    borderWidth:1,
    borderColor:'grey',
    marginVertical:5,
  },
  optionText:{
    fontSize:18,
  },
  hiText:{
   fontSize:19,
    color:'white'
  },
  logoutView:{
    alignSelf:'flex-end',
  },
  logoutImage:{
    height:30,
    width:30,
  },
  touchableLogout:{
    alignSelf:'center'
  },
})
export default styles